/**
 * Barrel exports for canvas geometry/math/hit-test helpers. None of these
 * touch React state — they're pure functions over `Molecule` and primitives.
 */
export type { Point, Viewport } from './polygons';
export { polygonArea, pointInPolygon, findRingsAtPoint, findSmallestRingAtPoint } from './polygons';
export {
  angle0To2Pi,
  shortestAngleDiff,
  pointSegDist,
  snapSegmentEndpointToAngleStep,
  snapAngleToStepRad,
} from './angles';
export { hexToRgba } from './colors';
export {
  BOND_TRIM_GAP_C,
  BOND_TRIM_GAP_HETERO,
  CONDENSED_TERMINAL_BOND_PAD_PX,
  condensedTerminalBondInsetPx,
  shouldTrimBondEndpoints,
  bondEndPoints,
  bondStrokeColor,
  type BondTrimContext,
} from './bondGeometry';
export {
  measureAliasLabelSize,
  measureHeadAnchoredLabelSize,
  aliasLabelBondGapTowardPartnerPx,
  labelBoxBondGapTowardPartnerPx,
} from './aliasLabelMetrics';
export { computeAutoExtendAngle } from './autoExtendAngle';
export {
  IMPLICIT_H_LABEL_DIST,
  IMPLICIT_H_BOND_END,
  implicitHydrogenLabelDist,
  implicitHydrogenBondEnd,
  hGoesLeft,
  carbonLabelHGoesLeft,
  getHydrogenStubDirections,
} from './hydrogenLayout';
export {
  getLonePairPlacements,
  labelBoxFromExtents,
  resolveLonePairWorldPoint,
  LONE_PAIR_DIST_PX,
  LONE_PAIR_DOT_SEP_PX,
  LONE_PAIR_DOT_R_PX,
  RADICAL_DIST_PX,
  RADICAL_DOT_R_PX,
  type LabelBoxLocal,
  type LonePairPlacement,
  type LonePairPreferSide,
  type Point2,
} from './lonePairLayout';
export {
  buildCanvasTextFont,
  buildCanvasTextFontAtSize,
  canvasTextEffectiveFontSize,
  canvasTextLineHeight,
  canvasTextAlign,
  wrapCanvasTextLines,
  wrapCanvasTextLinesIndexed,
  measureCanvasTextBox,
  measureCanvasTextContentSize,
  getCanvasTextBox,
  canvasTextEditorLayout,
  canvasTextFitContentPatch,
  resolveCanvasTextInk,
  estimateCanvasTextAabb,
  pickCanvasTextAt,
  pickCanvasTextContentAt,
  hitCanvasTextBox,
  canvasTextHitPadWorld,
  CANVAS_TEXT_IDLE_GRAB_PAD_PX,
  CANVAS_TEXT_SELECTED_GRAB_PAD_PX,
  pickCanvasTextResizeHandle,
  pickCanvasTextRotateHandle,
  canvasTextResizePatch,
  canvasTextRotatePatch,
  canvasTextCornerCursor,
  canvasTextCursorAt,
  canvasTextBbox,
  pickTopCanvasTextInRect,
  getCanvasTextCornerWorld,
  getCanvasTextRotateHandleWorld,
  getCanvasTextTopMidWorld,
  worldToTextLocal,
  textLocalToWorld,
  type CanvasTextBox,
  type CanvasTextResizeCorner,
  type WrappedCanvasTextLine,
} from './canvasText';
export {
  CANVAS_TEXT_SCRIPT_SCALE,
  canvasTextScriptDy,
  normalizeTextScriptRanges,
  resolveCanvasTextScripts,
  scriptAtIndex,
  selectionHasUniformScript,
  toggleTextScriptRange,
  remapTextScriptRanges,
  inferTextEdit,
  type CanvasTextScriptKind,
  type CanvasTextScriptRange,
} from './canvasTextScripts';
export { bestSproutAngle, bestRingAttachGrowAngle } from './sproutAngle';
export {
  pickSruBracketAt,
  sruBracketLabelBounds,
  type SruBracketHit,
} from './sruBracket';
export {
  ROTATE_HANDLE_R,
  ROTATE_HANDLE_OFFSET,
  MOVE_HANDLE_R,
  MOVE_HANDLE_OFFSET,
  SCALE_HANDLE_R,
  TRANSFORM_PAD,
  TRANSFORM_MIN_SPAN,
  type SelectionAabb,
  type SelectionTransformLayout,
  estimateLabelTextAabb,
  estimateAliasLabelAabb,
  getSelectionAabb,
  getMarqueeSelectionAabb,
  getMarqueeSelectionTransformLayout,
  hasMarqueeSelectionContent,
  type MarqueeSelectionBoundsInput,
  getSelectionCentroid,
  getSelectionTransformLayout,
  isNearTransformRotateHandle,
  isNearTransformScaleHandle,
  pickTransformScaleHandle,
  getSelectionBoxHandles,
  anchorForBoxHandle,
  isUniformBoxHandle,
  scaleFactorsForBoxHandle,
  BOX_CORNER_HANDLE,
  BOX_EDGE_HANDLE,
  type SelectionBoxHandle,
  isNearTransformMoveHandle,
  isInsideSelectionTransformBox,
  collectAtomIdsFromLasso,
  expandAtomIdsToConnectedFragments,
  atomIdsForSelectionTransform,
} from './selection';
export { applyMarqueeMovePreview, type MarqueeMovePreviewIds } from './marqueePreview';
export { getSmallestRingCenter, getSmallestCycleAtomIds } from './rings';
export {
  collectAromaticCircles,
  AROMATIC_CIRCLE_INSET,
  MIN_AROMATIC_CIRCLE_ATOMS,
  MAX_AROMATIC_CIRCLE_ATOMS,
  type AromaticCircle,
} from './aromaticCircles';
export {
  pickCanvasOrbitalAt,
  resolveOrbitalCenter,
  orbitalSupportsRotation,
  getOrbitalRotateHandleWorld,
  pickOrbitalRotateHandle,
  canvasOrbitalRotatePatch,
  canvasOrbitalWithDragPreview,
} from './orbitals';
export {
  getMoleculeRevisionCache,
  clearMoleculeRevisionCache,
  type MoleculeRevisionCache,
} from './moleculeRevisionCache';
export { functionalGroupAtomIds, sharedFunctionalGroupAtomIds } from './functionalGroupHover';
export {
  buildSpatialGrid,
  getSpatialGridForMolecule,
  queryAtomIdsInRect,
  queryAtomIdsNear,
  type SpatialGrid,
} from './spatialGrid';
export {
  worldViewportRect,
  cullFragmentsToViewport,
  LOD_LABEL_MIN_ZOOM,
  type WorldViewport,
  type CulledSets,
} from './viewportCull';
export {
  canvasCssSize,
  canvasBackingDpr,
  readDevicePixelRatio,
  clampBackingDpr,
  syncCanvasBackingStore,
  MAX_CANVAS_DEVICE_PIXEL_RATIO,
  type CssSize,
} from './canvasResolution';
export {
  drawReactionArrowCanvas,
  drawReactionArrowShape,
  pickReactionArrowAt,
  reactionArrowAfterDelta,
  offsetReactionArrowForDrag,
  defaultCurveControl,
  defaultSCurveControls,
  defaultCycleArcCenter,
  getReactionArrowKind,
  sampleReactionArrowPolyline,
  sampleCycleArcPolyline,
  resolveCycleArc,
  pickReactionArrowEndpoint,
  pickReactionArrowCurveHandle,
  getReactionArrowCurveHandleWorld,
  listReactionArrowEditHandles,
  arrowsForHitTest,
  arrowHandleHitTolWorld,
  reagentSlotChipHitTolWorld,
  reactionArrowCurveHandlePatch,
  reactionArrowEndpointResizePatch,
  isQuadraticCurvedArrowKind,
  isFreeformCurveArrowKind,
  isOrthogonalPolylineArrowKind,
  quadControlFromOnCurveMid,
  defaultPathPoints,
  defaultRowWrapPathPoints,
  resolvePathPoints,
  reactionArrowReagentLabelAnchor,
  reactionArrowReagentSlotPositions,
  reactionArrowSelectionAabb,
  pickReactionArrowReagentSlot,
  type ReactionArrowReagentSlot,
  type ReactionArrowEndpoint,
  type ReactionArrowEditHandle,
} from './reactionArrow';
export { buildReactionArrowFromDrag } from './reactionArrowFromDrag';
export {
  normalizeShapeBox,
  hitCanvasShape,
  pickCanvasShapeAt,
  strokeShapeKind,
  conicalFlaskPathInBox,
  drawConicalFlaskInBox,
  drawBeakerInBox,
  drawTestTubeInBox,
  drawRoundBottomFlaskInBox,
  drawCondenserInBox,
  drawSeparatoryFunnelInBox,
  drawFilterFunnelInBox,
  drawDroppingFunnelInBox,
  drawThreeNeckRbfInBox,
  drawBuchnerFlaskInBox,
  drawClaisenAdapterInBox,
  drawDistillationHeadInBox,
  drawReceivingFlaskInBox,
  drawDeanStarkTrapInBox,
  drawGraduatedCylinderInBox,
  drawVolumetricFlaskInBox,
  drawChromatographyColumnInBox,
  drawTlcChamberInBox,
  drawAllihnCondenserInBox,
  drawDimrothCondenserInBox,
  drawSoxhletInBox,
  drawHirschFunnelInBox,
  drawSchlenkFlaskInBox,
  drawGasBubblerInBox,
  drawThermometerAdapterInBox,
  drawStraightAdapterInBox,
  drawVacuumAdapterInBox,
  drawBentAdapterInBox,
  drawVacuumTubingInBox,
  drawCoolantTubingInBox,
  drawStopperInBox,
  drawSeptumInBox,
  drawKeckClipInBox,
  drawBuchnerFunnelInBox,
  drawSinteredFunnelInBox,
  drawSyringeInBox,
  drawCannulaInBox,
  drawNmrTubeInBox,
  drawDryingTubeInBox,
  drawHeatingMantleInBox,
  drawOilBathInBox,
  drawIceBathInBox,
  drawDryIceBathInBox,
  drawChillerInBox,
  drawLabJackInBox,
  drawRetortStandInBox,
  drawThreeProngClampInBox,
  drawStirBarInBox,
  drawPasteurPipetteInBox,
  drawSpatulaInBox,
  drawPowderFunnelInBox,
  drawTwoNeckRbfInBox,
  drawVigreuxColumnInBox,
  drawCowReceiverInBox,
  drawColdFingerInBox,
  drawColdTrapInBox,
  drawVacuumPumpInBox,
  drawGasInletAdapterInBox,
  drawBalloonInBox,
  drawReducingAdapterInBox,
  drawRotovapBumpTrapInBox,
  drawRotovapFlaskInBox,
  drawHotplateStirrerInBox,
  drawDewarFlaskInBox,
  drawThermometerInBox,
  drawWatchGlassInBox,
  drawBuretteInBox,
  drawEvaporatingDishInBox,
  drawFilterAdapterInBox,
  drawPressureTubeInBox,
  drawDesiccatorInBox,
  drawPearShapedFlaskInBox,
  drawBunsenBurnerInBox,
  drawAlcoholLampInBox,
  drawSandBathInBox,
  drawSteamBathInBox,
  drawWaterBathInBox,
  drawHeatGunInBox,
  drawHeatingBlockInBox,
  drawOverheadStirrerInBox,
  drawFourNeckRbfInBox,
  drawRotovapBodyInBox,
  drawAspiratorInBox,
  drawVacuumGaugeInBox,
  drawGasCylinderInBox,
  drawFumeHoodInBox,
  drawWeighingBoatInBox,
  drawForcepsInBox,
  drawMortarPestleInBox,
  drawCrystallizingDishInBox,
  drawPetriDishInBox,
  drawHickmanHeadInBox,
  drawJacketedReactorInBox,
  drawSchlenkTubeInBox,
  drawGasDispersionTubeInBox,
  drawRingClampInBox,
  drawAnalyticalBalanceInBox,
  drawStemlessFunnelInBox,
  drawMetalJointClipInBox,
  drawGloveboxInBox,
  drawSchlenkManifoldInBox,
  drawFilterCannulaInBox,
  drawTransferNeedleInBox,
  drawPressureReactorInBox,
  drawMicrowaveReactorInBox,
  drawSyringePumpInBox,
  drawFlowReactorInBox,
  drawFlashSystemInBox,
  drawLyophilizerInBox,
  drawCentrifugeInBox,
  drawPhotoreactorInBox,
  drawElectrochemicalCellInBox,
  drawVacuumSublimatorInBox,
  drawKugelrohrInBox,
  drawSolventPurificationSystemInBox,
  drawTubeFurnaceInBox,
  drawMuffleFurnaceInBox,
  drawQuartzTubeInBox,
  drawQuartzBoatInBox,
  drawCrucibleInBox,
  drawTongsInBox,
  drawYoungStopcockInBox,
  drawSpinCoaterInBox,
  drawBiosafetyCabinetInBox,
  drawIncubatorShakerInBox,
} from './canvasShapes';
export {
  getCanvasShapeBox,
  getShapesWorldAabb,
  hitCanvasShapeTransformed,
  canvasShapeWithDragPreview,
  pickCanvasShapeResizeHandle,
  pickCanvasShapeRotateHandle,
} from './canvasShapeTransform';
export {
  hitCanvasImage,
  pickCanvasImageAt,
  getCanvasImageBox,
  pickCanvasImageResizeHandle,
  pickCanvasImageRotateHandle,
  canvasImageResizePatch,
  canvasImageRotatePatch,
  canvasImageWithDragPreview,
} from './canvasImages';
export { pickStrokeAt, pickStrokeInRect, pickStrokeInPolygon, collectStrokesInRect, collectStrokesInPolygon } from './strokes';
export {
  pickAnnotationInRect,
  pickAnnotationInPolygon,
  collectAnnotationsInRect,
  collectAnnotationsInPolygon,
  type AnnotationPick,
  type MarqueeAnnotationSet,
} from './annotationPick';
export { getChainPoints, chainVertexLabelOffset } from './chain';
export {
  type AlignmentGuides,
  collectAlignmentTargets,
  guidesForSelectionMove,
  guidesForCanvasTextMove,
  guidesForReactionArrowMove,
  guidesForReactionArrowResize,
  ARROW_ENDPOINT_AXIS_SNAP_WORLD,
  DEFAULT_GRID_SIZE,
  snapPointToGrid,
  snapSelectionMovePointer,
  snapReactionArrowMovePointer,
  snapReactionArrowResizePointer,
  alignmentGuideThresholdWorld,
} from './alignmentGuides';
